### ISSUE TITLE
DB schema generation doesn't work

### ISSUE THREAD

**Issue by airoasis** [AbsaOSS/vcxagencynode#150]
I'm still using the v0.3.0, and found the issue when starting the application. 
If I use the DB account other than the 'postgres' user, it doesn't work. 

```
mediator-78576444f-bbbd8 mediator   "LOG_LEVEL": "silly",
mediator-78576444f-bbbd8 mediator   "LOG_ENABLE_INDYSDK": "true",
mediator-78576444f-bbbd8 mediator   "LOG_JSON_TO_CONSOLE": "false",
mediator-78576444f-bbbd8 mediator   "SERVER_PORT": 8080,
mediator-78576444f-bbbd8 mediator   "SERVER_MAX_REQUEST_SIZE_KB": 300,
mediator-78576444f-bbbd8 mediator   "SERVER_ENABLE_TLS": "false",
mediator-78576444f-bbbd8 mediator   "AGENCY_WALLET_NAME": "vcxagency-node",
mediator-78576444f-bbbd8 mediator   "AGENCY_DID": "VsKV7grR1BUE29mG2Fm2kX",
mediator-78576444f-bbbd8 mediator   "AGENCY_SEED_SECRET": "0******************************d",
mediator-78576444f-bbbd8 mediator   "AGENCY_WALLET_KEY_SECRET": "0******************9",
mediator-78576444f-bbbd8 mediator   "AGENCY_TYPE": "enterprise",
mediator-78576444f-bbbd8 mediator   "PG_STORE_HOST": "postgres",
mediator-78576444f-bbbd8 mediator   "PG_STORE_PORT": 5432,
mediator-78576444f-bbbd8 mediator   "PG_STORE_ACCOUNT": "mediator",
mediator-78576444f-bbbd8 mediator   "PG_STORE_PASSWORD_SECRET": "a*****g",
mediator-78576444f-bbbd8 mediator   "PG_STORE_DATABASE": "agency-storage",
mediator-78576444f-bbbd8 mediator   "PG_WALLET_ACCOUNT": "mediator",
mediator-78576444f-bbbd8 mediator   "PG_WALLET_PASSWORD_SECRET": "a*****g",
mediator-78576444f-bbbd8 mediator   "PG_WALLET_ADMIN_ACCOUNT": "mediator",
mediator-78576444f-bbbd8 mediator   "PG_WALLET_ADMIN_PASSWORD_SECRET": "a*****g",
mediator-78576444f-bbbd8 mediator   "PG_WALLET_URL": "postgres:5432",
mediator-78576444f-bbbd8 mediator   "PG_WALLET_MAX_CONNECTIONS": 50,
mediator-78576444f-bbbd8 mediator   "PG_WALLET_CONNECTION_TIMEOUT_MINS": 30
mediator-78576444f-bbbd8 mediator }
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.593] [index] [debug] [expressRequestId=undefined]: Going to build application internals.
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.601] [app] [info] [expressRequestId=undefined]: Initializing postgres plugin with config: {"url":"postgres:5432","max_connections":50,"min_idle_count":0,"wallet_scheme":"MultiWalletSingleTableSharedPool"}
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.901] [app] [silly] [expressRequestId=undefined]: INDYSDK: prepare_result: >>> Ok(())
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.905] [app] [silly] [expressRequestId=undefined]: INDYSDK: indy_set_logger: <<< res: Success
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.907] [app] [silly] [expressRequestId=undefined]: INDYSDK: indy_get_logger >>> context_p: 0x4003567bf0, enabled_cb_p: 0x4003567bf8, log_cb_p: 0x4003567c30, flush_cb_p: 0x4003567c00
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.909] [app] [silly] [expressRequestId=undefined]: INDYSDK: indy_get_logger: <<< res: Success
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.911] [app] [silly] [expressRequestId=undefined]: INDYSDK: indy_register_wallet_type: >>> command_handle: 1, type_: 0x4002004de0, cb: Some(0x40072b2270)
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.913] [app] [silly] [expressRequestId=undefined]: INDYSDK: indy_register_wallet_type: params type_: "postgres_storage"
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.915] [app] [silly] [expressRequestId=undefined]: INDYSDK: prepare_result: >>> Ok(())
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.917] [app] [silly] [expressRequestId=undefined]: INDYSDK: indy_register_wallet_type: <<< res: Success
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.918] [app] [info] [expressRequestId=undefined]: INDYSDK: Worker thread started
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.920] [app] [debug] [expressRequestId=undefined]: INDYSDK: WalletCommand command received
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.922] [app] [debug] [expressRequestId=undefined]: INDYSDK: RegisterWalletType command received
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.923] [app] [silly] [expressRequestId=undefined]: INDYSDK: _register_type >>> type_: "postgres_storage"
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.925] [app] [silly] [expressRequestId=undefined]: INDYSDK: register_wallet_storage >>> type_: "postgres_storage"
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.926] [app] [silly] [expressRequestId=undefined]: INDYSDK: register_wallet_storage <<<
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.927] [app] [silly] [expressRequestId=undefined]: INDYSDK: _register_type <<< res: ()
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.928] [app] [silly] [expressRequestId=undefined]: INDYSDK: prepare_result: >>> Ok(())
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.930] [app] [silly] [expressRequestId=undefined]: INDYSDK: indy_register_wallet_type: cb command_handle: 1, err: Success
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.931] [app] [debug] [expressRequestId=undefined]: INDYSDK: Initialising postgresql using MultiWalletSingleTableSharedPool strategy.
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.933] [app] [debug] [expressRequestId=undefined]: INDYSDK: MultiWalletSingleTableStrategySharedPool open >> building connection pool
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.934] [app] [error] [expressRequestId=undefined]: INDYSDK: Init storage failed: IOError("IO error during storage operation: database error")
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:27.977] [pgstorage-entities] [warn] [expressRequestId=undefined]: Couldn't connect to postgres, will try again after 2000ms.
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:30.001] [pgstorage-entities] [warn] [expressRequestId=undefined]: Couldn't connect to postgres, will try again after 2000ms.
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:32.014] [pgstorage-entities] [warn] [expressRequestId=undefined]: Couldn't connect to postgres, will try again after 2000ms.
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:34.029] [pgstorage-entities] [warn] [expressRequestId=undefined]: Couldn't connect to postgres, will try again after 2000ms.
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:36.038] [pgstorage-entities] [warn] [expressRequestId=undefined]: Couldn't connect to postgres, will try again after 2000ms.
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:38.054] [index] [error] [expressRequestId=undefined]: Unhandled error. Application will be terminated. Error: Couldn't connect to postgres after 5 attempts.
mediator-78576444f-bbbd8 mediator     at waitUntilConnectsToPostgres (/home/node/vcxagency-node/src/service/storage/pgstorage-entities.js:46:13)
mediator-78576444f-bbbd8 mediator     at processTicksAndRejections (internal/process/task_queues.js:97:5)
mediator-78576444f-bbbd8 mediator     at async buildApplication (/home/node/vcxagency-node/src/setup/app.js:109:3)
mediator-78576444f-bbbd8 mediator     at async run (/home/node/vcxagency-node/src/index.js:65:25)
mediator-78576444f-bbbd8 mediator [2022-03-17 11:23:38.056] [index] [warn] [expressRequestId=undefined]: Process exiting with code: 255
mediator-78576444f-bbbd8 mediator npm ERR! code ELIFECYCLE
mediator-78576444f-bbbd8 mediator npm ERR! errno 255
mediator-78576444f-bbbd8 mediator npm ERR! vcxagency-node@1.0.0 serve: `NODE_ENV=production node src/index.js`
mediator-78576444f-bbbd8 mediator npm ERR! Exit status 255
mediator-78576444f-bbbd8 mediator npm ERR!
mediator-78576444f-bbbd8 mediator npm ERR! Failed at the vcxagency-node@1.0.0 serve script.
mediator-78576444f-bbbd8 mediator npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
mediator-78576444f-bbbd8 mediator
mediator-78576444f-bbbd8 mediator npm ERR! A complete log of this run can be found in:
mediator-78576444f-bbbd8 mediator npm ERR!     /home/node/.npm/_logs/2022-03-17T02_23_38_190Z-debug.log
```

**Comment by airoasis** [comment]
Hi guys. How have you been? We are still using the old version of vcxagencynode, and found an issue while we were migrating the DB to a new instance. I just look through code written in node, and I couldn't find any issue... Can you please look into this?

**Comment by airoasis** [comment]
Please disregard this open issue. We are going to use the latest version (, that is MySQL). Close the issue.
